name: "Refresh jdk21u-dev from Upstream"
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
    refresh-jdk21-dev:
        runs-on: ubuntu-latest
        name: "Update Corretto-21 nightly"
        if: github.repository_owner == 'corretto'
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: "Fetch Corretto-21"
              uses: ./.github/actions/fetch-repo
              with:
                upstream: 'https://github.com/openjdk/jdk21u-dev.git'
                local-branch: 'upstream-jdk21u-dev'
            - name: "Merge Corretto-21"
              uses: ./.github/actions/merge-repo
              with:
                upstream: 'upstream-jdk21u-dev'
                merge-branch: 'nightly'
            - name: "Update Corretto version"
              uses: ./.github/actions/update-version
              with:
                upstream: 'upstream-jdk21u-dev'
                version-branch: 'nightly'
